"""Add prep_time, cook_time, servings to Recipe

Revision ID: 180b43ca1bb7
Revises: ff2755e5c38c
Create Date: 2025-05-03 11:10:23.607159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180b43ca1bb7'
down_revision = 'ff2755e5c38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cook_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('servings', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('servings')
        batch_op.drop_column('cook_time')
        batch_op.drop_column('prep_time')

    # ### end Alembic commands ###
